# Wait for webhook approval
on:
    repository_dispatch:
      types: [vercel-approve-deploy]
  
jobs:
    deploy:
      if: github.event.client_payload.commit_sha == github.sha
      runs-on: ubuntu-latest
      steps:
        - name: Trigger Vercel Deployment
          id: deploy
          run: |
            DEPLOY_RESPONSE=$(curl -s -X POST "${{ secrets.VERCEL_DEPLOY_HOOK }}")
            if [ $? -eq 0 ]; then
              echo "✅ Deployment triggered successfully"
            else
              echo "❌ Failed to trigger deployment"
              exit 1
            fi
  
        - name: Wait for Deployment
          run: |
            echo "Waiting for deployment to complete..."
            sleep 30
  
        - name: Send Success Notification
          if: success()
          uses: dawidd6/action-send-mail@v3
          with:
            server_address: ${{ secrets.SMTP_SERVER }}
            server_port: ${{ secrets.SMTP_PORT }}
            username: ${{ secrets.SMTP_USERNAME }}
            password: ${{ secrets.SMTP_PASSWORD }}
            subject: "✅ Deployment Successful - ${{ github.repository }}"
            body: |
              Deployment completed successfully!
  
              Repository: ${{ github.repository }}
              Branch: ${{ github.ref_name }}
              Commit: ${{ github.sha }}
              Deployment URL: ${{ secrets.VERCEL_APP_URL }}
  
              View deployment: ${{ secrets.VERCEL_APP_URL }}
              View changes: ${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}
            to: ${{ secrets.APPROVER_EMAIL_1 }},${{ secrets.APPROVER_EMAIL_2 }}
            from: "GitHub Actions <${{ secrets.SMTP_USERNAME }}>"