name: Deploy to Vercel (Dev) with Approval

on:
  workflow_dispatch:
    inputs:
      approval:
        description: "Enter 'allow' to approve or 'deny' to reject the deployment"
        required: true
        default: "deny"

jobs:
  approval-check:
    runs-on: ubuntu-latest
    steps:
      - name: Validate Input
        run: |
          APPROVAL="${{ github.event.inputs.approval }}"
          if [[ -z "$APPROVAL" || "$APPROVAL" != "allow" ]]; then
            echo "❌ Deployment Denied. Exiting..."
            exit 1
          fi
          echo "✅ Deployment Approved. Proceeding..."

  trigger-deployment:
    needs: approval-check
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Vercel
        run: |
          RESPONSE=$(curl -X POST "https://api.vercel.com/v1/integrations/deploy/prj_7Jux9bzyf3Krx6XMPBedfhn2PkNJ/2dUuDfemMp")
          echo "Vercel Deployment Response: $RESPONSE"

      - name: Notify Deployment Success
        if: success()
        run: echo "✅ Deployment to Dev was successful!"